/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogArticle {
  'title' : string,
  'date' : Time,
  'readTime' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface CaseStudy {
  'result' : string,
  'title' : string,
  'challenge' : string,
  'strategy' : string,
  'industry' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Testimonial {
  'review' : string,
  'starRating' : bigint,
  'clientName' : string,
  'role' : string,
  'company' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllBlogArticles' : ActorMethod<[], Array<BlogArticle>>,
  'getAllCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogArticleByTitle' : ActorMethod<[string], BlogArticle>,
  'getCaseStudyByTitle' : ActorMethod<[string], CaseStudy>,
  'getContactSubmissionByTimestamp' : ActorMethod<[string], ContactSubmission>,
  'getTestimonialByClientName' : ActorMethod<[string], Testimonial>,
  'submitContact' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];