/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogArticle = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'readTime' : IDL.Nat,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const CaseStudy = IDL.Record({
  'result' : IDL.Text,
  'title' : IDL.Text,
  'challenge' : IDL.Text,
  'strategy' : IDL.Text,
  'industry' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'review' : IDL.Text,
  'starRating' : IDL.Nat,
  'clientName' : IDL.Text,
  'role' : IDL.Text,
  'company' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
  'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogArticleByTitle' : IDL.Func([IDL.Text], [BlogArticle], ['query']),
  'getCaseStudyByTitle' : IDL.Func([IDL.Text], [CaseStudy], ['query']),
  'getContactSubmissionByTimestamp' : IDL.Func(
      [IDL.Text],
      [ContactSubmission],
      ['query'],
    ),
  'getTestimonialByClientName' : IDL.Func([IDL.Text], [Testimonial], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogArticle = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'readTime' : IDL.Nat,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const CaseStudy = IDL.Record({
    'result' : IDL.Text,
    'title' : IDL.Text,
    'challenge' : IDL.Text,
    'strategy' : IDL.Text,
    'industry' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'review' : IDL.Text,
    'starRating' : IDL.Nat,
    'clientName' : IDL.Text,
    'role' : IDL.Text,
    'company' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
    'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogArticleByTitle' : IDL.Func([IDL.Text], [BlogArticle], ['query']),
    'getCaseStudyByTitle' : IDL.Func([IDL.Text], [CaseStudy], ['query']),
    'getContactSubmissionByTimestamp' : IDL.Func(
        [IDL.Text],
        [ContactSubmission],
        ['query'],
      ),
    'getTestimonialByClientName' : IDL.Func(
        [IDL.Text],
        [Testimonial],
        ['query'],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };